fetch_ball when ball is close and not in front
RoboCup-MSL/MRA-components pull request #13
Opened 2023-10-31 06:13 UTC by jveijck

fixes for issue #8.
extende geometry library when functions which are generic and already present in a component (refactoring)

2023-10-31 11:25 UTC, jveijck commented on components/falcons/getball_fetch/tick.cpp
> +            if (target.rz > MRA::Geometry::deg_to_rad(params.rotation_only_angle())
fabs(target.rz) should be used.

2023-11-01 18:50 UTC, janfeitsma requested changes

2023-11-01 18:50 UTC, janfeitsma commented on components/falcons/getball_fetch/interface/Params.proto
> +    float rotation_only_angle = 4; // // rotate only if max angle to ball [degrees) - applied to both sides of the front
The SI unit of angular measure is the radian, let's use that instead of degrees.

Good parameterization though.

2023-11-01 18:50 UTC, janfeitsma commented on components/falcons/getball_fetch/interface/Params.proto
> +    float rotation_only_distance = 3; // rotate only if distance to ball [meters]
Nitpicking: in this component we use camelCase. I prefer consistency

2023-11-01 18:50 UTC, janfeitsma commented on libraries/geometry/position.hpp
> +    double distanceXY(const MRA::Geometry::Position& r_position); // xy-distance to other position
This function could be replaced by using Pose operator- and size().

double distance = (pos - otherpos).size();

I prefer to keep the interface clean.

2023-11-01 20:24 UTC, jveijck commented on components/falcons/getball_fetch/interface/Params.proto
> +    float rotation_only_angle = 4; // // rotate only if max angle to ball [degrees) - applied to both sides of the front
Indeed SI unit of angular measure is radian, but for most humans that is hard to interpretate. In the calculations radians is used. It is converted to radians.

2023-11-01 20:25 UTC, jveijck commented on components/falcons/getball_fetch/interface/Params.proto
> +    float rotation_only_distance = 3; // rotate only if distance to ball [meters]
updated

2023-11-01 20:55 UTC, jveijck commented on components/falcons/getball_fetch/interface/Params.proto
> +    float rotation_only_angle = 4; // // rotate only if max angle to ball [degrees) - applied to both sides of the front
It can be changed, but personally I prefer use degrees for the user. I consider the json file as an interface for the user.
Still want to change it to radians ? In ProofAlive also degrees are used.

2023-11-02 15:19 UTC, janfeitsma commented on components/falcons/getball_fetch/interface/Params.proto
> +    float rotation_only_angle = 4; // // rotate only if max angle to ball [degrees) - applied to both sides of the front
I still slightly prefer consistency - now we have pose.rz in radians at various places on the interface.
But OK for now. I do like that it is easier to configure.

2023-11-02 15:19 UTC, merged