Introduction Local Ball Tracking component
RoboCup-MSL/MRA-components pull request #20
Opened 2023-11-19 20:20 UTC by jveijck

Introduction of new component: Local Ball Tracking.
README.adoc contains the technical description.

In near future additional test-cases and some refactoring can be expected.

2023-11-21 20:40 UTC, janfeitsma requested changes

2023-11-21 20:40 UTC, janfeitsma commented on components/robotsports/local_ball_tracking/test.cpp
> +    MRA_LOG_INFO("> %s::%s", testsuitename.c_str(), testname.c_str());
The macro `MRA_TRACE_TEST_FUNCTION` is supposed to log testsuite name and test name, intended specifically for TEST context. This is a helper function.

See option `--tracing` to `MRA-build.py`. I don't think INFO is proper to use as debugging. (We might choose to make a console logger with default level INFO.)

2023-11-21 20:40 UTC, janfeitsma commented on components/robotsports/local_ball_tracking/test.cpp
> +static void config_MRA_logger(std::string component)
Surprised to see this logger configuration in code. The intent was to do this via shm. Doesn't that work for you / what needs to be improved at facility level?

2023-11-21 20:40 UTC, janfeitsma commented on components/robotsports/local_ball_tracking/CMakeLists.txt
> +# it should NOT be modified by user
I think the template is incorrect: currently user needs to handcraft CMakeLists.txt.

2023-11-21 20:40 UTC, janfeitsma commented on components/robotsports/local_ball_tracking/README.adoc
> +It is not following the MSL Reference Architecture as intended.
Well, having state fully controllable and observable is not mandatory, as it also brings potential performance problems. I consider it good practice, nice to have (for test suites).

2023-11-21 20:40 UTC, janfeitsma commented on components/robotsports/local_ball_tracking/interface/Input.proto
> +    repeated BallCandidate omnivision_balls = 1;  // ball candidates from omnivision camera (360 degrees)  - sensor type as enum - see velocity control
As you wrote in comment: why not define some sensor type enum and have one array of BallCandidates. Seems more scalable / generalizable for other teams who may use other sensors.

How specific is this algorithm to those sensors? We at Falcons use "multicam" (4 frontcams, kind of).

2023-11-21 20:40 UTC, janfeitsma commented on components/robotsports/local_ball_tracking/interface/Input.proto
> +    double confidence = 4;  // ball confidence [0..1] from sensor system (camera)
Consider to enumerate consecutively.

2023-11-21 20:49 UTC, jveijck commented on components/robotsports/local_ball_tracking/CMakeLists.txt
> +# it should NOT be modified by user
will update the template text

2023-11-21 20:53 UTC, jveijck commented on components/robotsports/local_ball_tracking/interface/Input.proto
> +    repeated BallCandidate omnivision_balls = 1;  // ball candidates from omnivision camera (360 degrees)  - sensor type as enum - see velocity control
Indeed, interface can be more generic, in case a team has a front, a left, a right and back camera (4 camera system as Falcons have) or using one or more llidar systems

In that case the predecessor need to be updated to support that configuration.
Future work.

2023-11-21 22:10 UTC, jveijck commented
@janfeitsma updates made based on your review comments.

2023-11-23 17:11 UTC, janfeitsma approved these changes

2023-11-23 18:38 UTC, merged