Local Ball Tracking: split in smaller components
RoboCup-MSL/MRA-components pull request #21
Opened 2023-12-01 23:15 UTC by jveijck

Split the local ball tracking in 3 components to make it more generic.
The original local ball tracking consists of two steps: preprocessor and tracking.
These are separated and a new local ball component is introduced, this component combines the two steps.
It allow to use local ball tracking without the preprocessor. 

Others:
- converted tabs to spaces (editor issue from the past): 
   - Installed tabs-to-space: "npm install -g tabs-to-spaces"
   - executed "find . -name '*.cpp' -exec t2s --spaces 4 {}" (and hpp)
- Introduction of BallCandidate and TrackedObject in datatypes.
  - TrackedObject can be reused for ObjectTracking in near future

2023-12-03 10:16 UTC, janfeitsma commented on components/robotsports/local_ball/README.adoc
> +It is not following the MSL Reference Architecture as intended.
About the 'intended' comment, if there is the desire to do so (not yet I think), we could add something in documentation about observable and controllable state. General best practice, reasons + examples to deviate. Then we could refer to it here.

2023-12-03 10:25 UTC, janfeitsma commented
Thanks about the de-tabbing, including fixing a slightly embarrassing amount on my side of the code base :).

2023-12-03 10:57 UTC, janfeitsma requested changes
Small typos.

Only discussion point is the input interface - how to define BallCandidate (or more general ObjectCandidate) in a reusable and future-proof manner

2023-12-03 10:57 UTC, janfeitsma commented on components/robotsports/local_ball/README.adoc
> +* add multiple ball candidates (simulating fake balls or ball furhter away)
typo

2023-12-03 10:57 UTC, janfeitsma commented on components/robotsports/local_ball/interface/Input.proto
> +    repeated MRA.Datatypes.BallCandidate omnivision_balls = 1;  // ball candidates from omnivision camera (360 degrees)  - sensor type as enum - see velocity control
The comment about the enum is a TODO item actually, right? Otherwise confusing.

Since you propose a new shared data type (which will be harder to change later), maybe now is the time to address it.

2023-12-03 10:57 UTC, janfeitsma commented on datatypes/BallCandidate.proto
> +    MRA.Datatypes.Pose measured_pose_fcs = 1;
It is not obvious why a measurement is expected in FCS rather than RCS.
This needs an explanation somewhere.

2023-12-03 10:57 UTC, janfeitsma commented on datatypes/BallCandidate.proto
> +    double sigma = 3; // ???? ==> variance on measured position
There are some things on this data type which I find not very generic / "MSL-average".
Why not remove sigma, make such things configurable at component level. (Looks functionally similar to `confidence`.)
In my opinion the property `is_free` should not be part of input candidates, but output - determined by algorithm.
The property `in_air` is double w.r.t. `z` in the coordinate. (Typically along with a threshold in component parameterization.)

Maybe we should discuss in next discord call? Better a little bit of effort & discussion now, than having to cleanup later.

Other MSL-fellow opinions are welcome too of course!

2023-12-03 10:57 UTC, janfeitsma commented on datatypes/TrackedObject.proto
> +message TrackedObject
This looks nicely reusable for ball / opponent / obstacle / human tracking!

Only thing I miss: an `id` integer. OK to leave for later. Applications for such an `id` are more on strategy side, for instance be able to assign a defense guard to a tracked opponent, while not being sensitive to things like numerical noise on proximity.

2023-12-03 10:57 UTC, janfeitsma commented on components/robotsports/local_ball_tracking/internal/sequence_clustering_common_defintions.hpp
> +        int  type;                     /* sensor label */
typo in filename

2023-12-03 10:57 UTC, janfeitsma commented on components/robotsports/local_ball_preprocessor/interface/Output.proto
> +    repeated MRA.Datatypes.BallCandidate candidates = 1;
Related to the discussion we probably need to have about the common BallCandidate. I find the act of `pre-processing` relatively algorithm-specific. Maybe the data type can be defined here to combine generic and specific elements?

2023-12-03 21:19 UTC, jveijck commented on components/robotsports/local_ball/README.adoc
> +It is not following the MSL Reference Architecture as intended.
added extra remark about observing the state.

2023-12-05 20:42 UTC, janfeitsma commented
Bazel build gives the following warning. I think the offending line can be safely removed.

```
WARNING: components/robotsports/local_ball_tracking/internal/BUILD.bazel:1:11: in includes attribute of cc_library rule //components/robotsports/local_ball_tracking/internal:LocalBallTracking: '..' resolves to 'components/robotsports/local_ball_tracking' not below the relative path of its package 'components/robotsports/local_ball_tracking/internal'. This will be an error in the future
```

2023-12-07 21:32 UTC, jveijck commented on datatypes/BallCandidate.proto
> +    MRA.Datatypes.Pose measured_pose_fcs = 1;
is added to to this proto file.

2023-12-07 21:36 UTC, jveijck commented on datatypes/BallCandidate.proto
> +    double sigma = 3; // ???? ==> variance on measured position
is_free and in_air are removed from interface, handled in local ball tracking. In first part of the algorithm.

2023-12-07 21:36 UTC, jveijck commented on datatypes/TrackedObject.proto
> +message TrackedObject
Added id.

2023-12-07 21:37 UTC, jveijck commented on components/robotsports/local_ball_preprocessor/interface/Output.proto
> +    repeated MRA.Datatypes.BallCandidate candidates = 1;
preprocessor is only removing observations. No need to added extra info here on the interface.

2023-12-07 21:43 UTC, jveijck commented on components/robotsports/local_ball/test.cpp
> +// Test shall run OK and return error_value 0.
updated

2023-12-15 21:39 UTC, jveijck commented
@janfeitsma buildserver is using bazel 7.x, the syntax is changed. Can you help

2023-12-16 08:53 UTC, janfeitsma commented
> @janfeitsma buildserver is using bazel 7.x, the syntax is changed. Can you help

Sure. I don't feel like upgrading right now, so I'll just explicitly let the workflows stick to bazel 6.4.0.

2023-12-16 09:20 UTC, merged