Local Obstacle Tracking
RoboCup-MSL/MRA-components pull request #22
Opened 2023-12-14 22:51 UTC by jveijck

Local Ball Tracking component : only using local sensorred data
- First working version with a simple testcase
- README added.
- Remaining work:
-- more test-cases
-- use parameters from protobuf (not hardcoded)
-- input field-configuration as input to cut off obstacles.

Ball Tracking introduction: 
Intend to combine output of local ball tracking (tracked object) and communicated poses of teammates.
to label tracked objects into  teammate or opponent (non-teammates)

2023-12-16 13:33 UTC, jveijck commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-std=c++17 -Wall -Werror -Wno-address -Wno-reorder -Wno-array-bounds -g")
-g should not be checked in (used for valgrind)

2023-12-16 13:33 UTC, jveijck commented on components/robotsports/local_obstacle_tracking/CMakeLists.txt
> +    PROPERTIES ENVIRONMENT "MRA_LOGGER_CONTEXT=unittest"
@janfeitsma is this correct?

2023-12-16 17:31 UTC, jveijck commented on components/robotsports/local_obstacle_tracking/CMakeLists.txt
> +    PROPERTIES ENVIRONMENT "MRA_LOGGER_CONTEXT=unittest"
Seems be correct. Is not related to Bazel, so can not be the cause of failing when running in bazel.

2023-12-30 13:43 UTC, jveijck commented
@janfeitsma I still have no clue why Bazel build fails on logging test. Any tips or tricks ? 
Can that longer time needed for testing is causing the issue ?

2024-01-04 20:09 UTC, janfeitsma requested changes
Few minor comments and suggestions on the failed tests.

2024-01-04 21:45 UTC, jveijck commented on MRA-build.py
> +        cmd = 'rm -rf /tmp/mra_logging_testsuites'
I will revert to avoid a possible side-effect.
Changed it because it would be more logical to start a folder with mra then testsuite (I had to look it up several times, after change to mra_ it was logical and i did not have to look it up again)

2024-01-04 21:45 UTC, jveijck commented on components/robotsports/local_obstacle_tracking/interface/Output.proto
> +    repeated MRA.Datatypes.TrackedObject objects = 1;
indeed, better name.

2024-01-04 21:45 UTC, jveijck commented on components/robotsports/obstacle_tracking/internal/BUILD.bazel
> +        "..",
I changed it for local_obstacle_tracking, but forgot this one.

2024-01-04 21:45 UTC, jveijck commented on components/robotsports/local_obstacle_tracking/interface/Input.proto
> +    MRA.Datatypes.Pose pose_fcs = 1;
obstacle tracking is open work. I started with one component which did tracking on measurements (by vision) and communication positions from teammates.  During the development I concluded that it was better to split these in two component. Obstacle Tracking with only local measurements and a second component which usage the output of the previous component (local_ball_tracking) and communicated positions of the team-mates to label the  tracked object in case it match with a team-mate.

2024-01-04 21:48 UTC, jveijck commented
> Few minor comments and suggestions on the failed tests.

2024-01-04 23:03 UTC, jveijck commented
@janfeitsma after reverting change in MRA-build.py, test still fails.  This excludes that the change in the file was the cause why the test fails.

2024-01-05 16:21 UTC, janfeitsma commented on components/robotsports/local_obstacle_tracking/internal/obstacle_tracking.cpp
> + *  @desc    determine best ball out of ball observations from various sensors
copy paste typo 'ball' instead of 'object' or 'obstacle'

2024-01-05 22:50 UTC, merged