Jve/doc updates
RoboCup-MSL/MRA-components pull request #26
Opened 2024-02-03 22:17 UTC by jveijck

updated documentation :
* added proof-is-alive documenation
* Object Coordinate System back to Robot Coordinates System.
* updated links

2024-02-08 17:47 UTC, janfeitsma requested changes

2024-02-08 17:47 UTC, janfeitsma commented on components/robotsports/proof_is_alive/README.adoc
> +Proof-is-Alive is an action that proofs the robot is a live. (on requested of the referee)
Typos (at several places): "prove". 

'proof' is a noun that refers to evidence that supports a conclusion, while 'prove' is a verb that means to demonstrate or make something known.

Maybe rename "prove_is_alive"?

2024-03-02 16:16 UTC, jveijck commented on components/robotsports/proof_is_alive/README.adoc
> +Proof-is-Alive is an action that proofs the robot is a live. (on requested of the referee)
renamed in documentation. Rename action will be done in a separate branch.

2024-04-18 17:00 UTC, janfeitsma approved these changes

2024-04-18 17:40 UTC, merged