Geometry library extension for pose and point
RoboCup-MSL/MRA-components pull request #43
Opened 2024-10-04 22:11 UTC by jveijck

2024-10-05 12:57 UTC, janfeitsma requested changes

2024-10-05 12:57 UTC, janfeitsma commented on libraries/geometry/point.cpp
> + * @return Normalized point. When input point has length 0, the result is (1,0)
That is not obvious and might cause trouble. 

Why not throw a runtime error "division-by-zero" instead?

2024-10-05 12:57 UTC, janfeitsma commented on libraries/geometry/point.hpp
> -    double size() const; // sqrt(x^2+y^2+z^2)
Use cases for point also include ball, which typically has z > 0. So I propose to make use of z and not drop it.

2024-10-05 13:19 UTC, jveijck commented on libraries/geometry/point.hpp
> -    double size() const; // sqrt(x^2+y^2+z^2)
the class point does not have no z. Therefore it should not be in the comment

2024-10-05 20:39 UTC, jveijck commented on libraries/geometry/point.cpp
> + * @return Normalized point. When input point has length 0, the result is (1,0)
agree, will throw std::range_error (range errors in internal computations)

2024-10-06 06:46 UTC, janfeitsma approved these changes

2024-10-06 06:46 UTC, janfeitsma commented on libraries/geometry/point.hpp
> -    double size() const; // sqrt(x^2+y^2+z^2)
Agree

2024-10-06 10:35 UTC, merged